import 'package:flutter/material.dart';

class Location {
  final String img;
  final String title;

  Location({required this.img, required this.title});
}

// Danh sách các tỉnh thành
List<Location> locationData = [
  Location(img: 'assets/images/63S/angiang.png', title: "An Giang"),
  Location(img: 'assets/images/63S/bacgiang.png', title: "Bắc Giang"),
  Location(img: 'assets/images/63S/backan.png', title: "Bắc Kạn"),
  Location(img: 'assets/images/63S/baclieu.png', title: "Bạc Liêu"),
  Location(img: 'assets/images/63S/bacninh.png', title: "Bắc Ninh"),
  Location(img: 'assets/images/63S/bentre.png', title: "Bến Tre"),
  Location(img: 'assets/images/63S/binhduong.png', title: "Bình Dương"),
  Location(img: 'assets/images/63S/binhdinh.png', title: "Bình Định"),
  Location(img: 'assets/images/63S/binhphuoc.png', title: "Bình Phước"),
  Location(img: 'assets/images/63S/binhthuan.png', title: "Bình Thuận"),
  Location(img: 'assets/images/63S/camau.png', title: "Cà Mau"),
  Location(img: 'assets/images/63S/cantho.png', title: "Cần Thơ"),
  Location(img: 'assets/images/63S/caobang.png', title: "Cao Bằng"),
  Location(img: 'assets/images/63S/daklak.png', title: "Đắk Lắk"),
  Location(img: 'assets/images/63S/daknong.png', title: "Đắk Nông"),
  Location(img: 'assets/images/63S/danang.png', title: "Đà Nẵng"),
  Location(img: 'assets/images/63S/dienbien.png', title: "Điện Biên"),
  Location(img: 'assets/images/63S/dongnai.png', title: "Đồng Nai"),
  Location(img: 'assets/images/63S/dongthap.png', title: "Đồng Tháp"),
  Location(img: 'assets/images/63S/gialai.png', title: "Gia Lai"),
  Location(img: 'assets/images/63S/hagiang.png', title: "Hà Giang"),
  Location(img: 'assets/images/63S/hanam.png', title: "Hà Nam"),
  Location(img: 'assets/images/63S/hanoi.png', title: "Hà Nội"),
  Location(img: 'assets/images/63S/hatinh.png', title: "Hà Tĩnh"),
  Location(img: 'assets/images/63S/haiduong.png', title: "Hải Dương"),
  Location(img: 'assets/images/63S/haiphong.png', title: "Hải Phòng"),
  Location(img: 'assets/images/63S/haugiang.png', title: "Hậu Giang"),
  Location(img: 'assets/images/63S/hoabinh.png', title: "Hòa Bình"),
  Location(img: 'assets/images/63S/hue.png', title: "Huế"),
  Location(img: 'assets/images/63S/hungyen.png', title: "Hưng Yên"),
  Location(img: 'assets/images/63S/khanhhoa.png', title: "Khánh Hòa"),
  Location(img: 'assets/images/63S/kiengiang.png', title: "Kiên Giang"),
  Location(img: 'assets/images/63S/kontum.png', title: "Kon Tum"),
  Location(img: 'assets/images/63S/laichau.png', title: "Lai Châu"),
  Location(img: 'assets/images/63S/lamdong.png', title: "Lâm Đồng"),
  Location(img: 'assets/images/63S/langson.png', title: "Lạng Sơn"),
  Location(img: 'assets/images/63S/laocai.png', title: "Lào Cai"),
  Location(img: 'assets/images/63S/longan.png', title: "Long An"),
  Location(img: 'assets/images/63S/namdinh.png', title: "Nam Định"),
  Location(img: 'assets/images/63S/nghean.png', title: "Nghệ An"),
  Location(img: 'assets/images/63S/ninhbinh.png', title: "Ninh Bình"),
  Location(img: 'assets/images/63S/ninhthuan.png', title: "Ninh Thuận"),
  Location(img: 'assets/images/63S/phutho.png', title: "Phú Thọ"),
  Location(img: 'assets/images/63S/phuyen.png', title: "Phú Yên"),
  Location(img: 'assets/images/63S/quangbinh.png', title: "Quảng Bình"),
  Location(img: 'assets/images/63S/quangnam.png', title: "Quảng Nam"),
  Location(img: 'assets/images/63S/quangngai.png', title: "Quảng Ngãi"),
  Location(img: 'assets/images/63S/quangninh.png', title: "Quảng Ninh"),
  Location(img: 'assets/images/63S/quangtri.png', title: "Quảng Trị"),
  Location(img: 'assets/images/63S/soctrang.png', title: "Sóc Trăng"),
  Location(img: 'assets/images/63S/sonla.png', title: "Sơn La"),
  Location(img: 'assets/images/63S/tayninh.png', title: "Tây Ninh"),
  Location(img: 'assets/images/63S/thaibinh.png', title: "Thái Bình"),
  Location(img: 'assets/images/63S/thainguyen.png', title: "Thái Nguyên"),
  Location(img: 'assets/images/63S/thanhhoa.png', title: "Thanh Hóa"),
  Location(img: 'assets/images/63S/tiengiang.png', title: "Tiền Giang"),
  Location(img: 'assets/images/63S/hcm.png', title: "TP Hồ Chí Minh"),
  Location(img: 'assets/images/63S/travinh.png', title: "Trà Vinh"),
  Location(img: 'assets/images/63S/tuyenquang.png', title: "Tuyên Quang"),
  Location(img: 'assets/images/63S/vinhlong.png', title: "Vĩnh Long"),
  Location(img: 'assets/images/63S/vinhphuc.png', title: "Vĩnh Phúc"),
  Location(img: 'assets/images/63S/yenbai.png', title: "Yên Bái"),
];
